# Multi-Pump-Interface
function S = addcomponents
% Function Information
% Parent - Pumps1.m
% Children - PanelSet.m
% Additions - S.fig
%           - S.pump
%           - S.ax
%           - S.im
%           - S.lb_quitone
%           - S.pb_quitone
%           - S.pb_quitall
% Description - Creates main figure and everything in it;
%               creates resizable figure, pump popup,
%               logo, quit buttons, and calls panel function

scrsz = get(0,'ScreenSize');
screensize_factor = 0.5;
clr = [1,1,1];  % color is dynamic
figsize = [(scrsz(3)*(1-screensize_factor))./2 (scrsz(4)*(1-screensize_factor))./2 ...
            scrsz(3)*screensize_factor scrsz(4)*screensize_factor];

% Master figure        
S.fig = figure('units','pixels','Position',figsize,...
              'menubar','none','name','Multi-Pump Driver Interface',...
              'numbertitle','off','resize','on','UserData',1,...
              'Visible','off','color',clr,'Tag','fig');%,'CloseRequestFcn',@SafeClose);
% Recipes Popup Menu          
S.recipe = uicontrol(S.fig,'style','pop','units','normalized',...
                   'position',[.28 .95 .205 .0355],'Tag','RO',...
                   'string',{'(select recipes here)',...
                             'recipe1',...
                             'recipe2',...
                             'recipe3',...
                             'recipe4'},...
                   'FontUnits','normalized'); 
          
% Pump Popup Menu          
S.pump = uicontrol(S.fig,'style','pop','units','normalized',...
                   'position',[.506 .95 .205 .0355],'Tag','PO',...
                   'string',{'(select pumps here)',...
                            'Syrris Asia Pump',...
                            'Little Things Factory Mr Q.',...
                            'Chemyx Nexus 3000',...
                            'Knauer Azura P4.1S',...
                            'Model 3HI Eldex'},...
                   'FontUnits','normalized');
               
% Other Devices Popup Menu          
S.device = uicontrol(S.fig,'style','pop','units','normalized',...
                   'position',[.732 .95 .205 .0355],'Tag','DO',...
                   'string',{'(select other devices here)',...
                             'Unistat 360',...
                             'Ika Plate'},...
                   'FontUnits','normalized');                

% Logo Display
S.ax = axes('Parent',S.fig,'units', 'normalized','position',[.01 .65 .25 .34],'Visible','off','ButtonDownFcn',{@logoFcn,S});
S.im = uicontrol('Parent',S.fig,'String','clse.png','Visible','off','Tag','im');
imshow(S.im.String);  

% Quit Buttons
S.lb_quitone = uicontrol(S.fig,'style','text','units','normalized','position',[.28 0.084 .716 0.04],...
                 'FontUnits','normalized','ForegroundColor',[1 1 1],'Tag','QL',...
                 'FontWeight','bold','string','No devices selected','BackgroundColor',[.90 .05 .05],'Visible','on');                
S.pb_quitone = uicontrol(S.fig,'style','push','units',S.lb_quitone.Units,'position',S.lb_quitone.Position,...
                 'FontUnits',S.lb_quitone.FontUnits,'ForegroundColor',S.lb_quitone.ForegroundColor,...
                 'FontWeight',S.lb_quitone.FontWeight,'string','QUIT','Tag','Q1',...
                 'BackgroundColor',S.lb_quitone.BackgroundColor,'callback',{@pb_call,S},'Visible','off');
S.pb_quitall = uicontrol(S.fig,'style','push','units','normalized',...
                 'position',[.28 0.037 .716 0.04],...
                 'FontUnits','normalized','ForegroundColor',S.lb_quitone.ForegroundColor,...
                 'FontWeight','bold','string','QUIT ALL DEVICES','Tag','QA',...
                 'BackgroundColor',S.lb_quitone.BackgroundColor,'callback',{@pb_call,S});

% Creates pump panels            
S = PanelSet(S,S.fig);
end
