# Multi-Pump-Interface
function S = Chemyx_Nexus3000_panel_setup(varargin)
% Parent - PanelSet.m
% Additions - S.Nexus 
% Description - Creates Chemyx Nexus 3000 panel and all of the
%               functions and interfaces associated with
%               this particular pump
S = varargin{1};
K = varargin{2}; %figure handle
%% Deconstruction
bor_w = S.panel_struct.bor_w;
bor_h = S.panel_struct.bor_h;
btn_w = S.panel_struct.btn_w;
btn_h = S.panel_struct.btn_h;
lbl_h = S.panel_struct.lbl_h;
flb_h = S.panel_struct.flb_h;
arr_w = S.panel_struct.arr_w;
panel_w = S.panel_struct.panel_w;
clr = S.panel_struct.clr;
edit_clr = S.panel_struct.edit_clr;
panpos = S.panel_struct.panpos;
coln = S.panel_struct.coln;
Max = S.panel_struct.Max;
Min = S.panel_struct.Min;
red = S.color.red;
blu = S.color.blu;
nex_blu = S.color.nex_blu;
grn = S.color.grn;
ppl = S.color.ppl;
org = S.color.org;
wht = S.color.wht;
blk = S.color.blk;
lit_red = S.color.lit_red;
lit_blu = S.color.lit_blu;
lit_grn = S.color.lit_grn;
lit_ppl = S.color.lit_ppl;
lit_org = S.color.lit_org;
jc = 0.12; %John's Constant :)
j2c = 0.31; %John's Second Constant :P

%% Nexus Panel
S.Nexus = uipanel('BorderType','none','BackgroundColor',clr,'Visible','off','Position',panpos,'Tag',strcat('Nexus_',num2str(K.UserData)));

%% Channel Control
S.column1 = uipanel(S.Nexus,'Visible','on','position',[0 0 panel_w/2 1],'BackgroundColor',nex_blu,'BorderType','none');%'etchedout');             
S.column2 = uipanel(S.Nexus,'Visible','on','position',[panel_w/2+0.01 0 panel_w-0.01 1],'BackgroundColor',nex_blu,'BorderType','none');%'etchedout');             
S.column2 = uipanel(S.Nexus,'Visible','on','position',[3*panel_w/2+0.01 0 panel_w/2 1],'BackgroundColor',nex_blu,'BorderType','none');%'etchedout');                 

%% %%%%%%%%%%%%%%%%%%%%%%% Pump figures go here

%% Labels
% Communication Settings
S.tit_comset = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(1) flooring(3.5,'fl') btn_w flb_h+0.02], 'max', 2,...
                 'FontUnits','normalized','FontWeight','bold', 'ForegroundColor', wht, 'FontSize', 0.4,...                 
                 'string','Communication Settings','BackgroundColor',nex_blu,'callback',{@pb_call,S});
S.port_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(1) flooring(2.9,'fl') btn_w/2 flb_h],...
                 'FontUnits','normalized','FontWeight','normal','ForegroundColor', wht,...                 
                 'string','Port I/O','BackgroundColor',nex_blu,'callback',{@pb_call,S});
S.baud_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(1) flooring(2.4,'fl') btn_w/2 flb_h],...
                 'FontUnits','normalized','FontWeight','normal','ForegroundColor', wht,...                 
                 'string','Baud Rate','BackgroundColor',nex_blu,'callback',{@pb_call,S});             
%Commands
S.tit_commands = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(1)+(btn_w*0.25/2)+0.03 flooring(8.5,'fl') btn_w-2*arr_w flb_h],...
                 'FontUnits','normalized','FontWeight','bold','ForegroundColor', wht, 'FontSize', 0.6,...                 
                 'string','Commands','BackgroundColor',nex_blu,'callback',{@pb_call,S});     
%Multi-Steps
S.multistep_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(2)+0.125 flooring(8.5,'fl') btn_w flb_h],...
                 'FontUnits','normalized','FontWeight','bold','ForegroundColor', wht, 'FontSize', 0.6,...                 
                 'string','Multi-Steps','BackgroundColor',nex_blu,'callback',{@pb_call,S});
S.unit_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(2)+0.015 flooring(7.9,'fl') btn_w/2 flb_h],...
                 'FontUnits','normalized','FontWeight','normal', 'ForegroundColor', wht,...                 
                 'string','Units','BackgroundColor',nex_blu,'callback',{@pb_call,S}); 
S.diameter_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(2) flooring(7.45,'fl') btn_w/2 flb_h],...
                 'FontUnits','normalized','FontWeight','normal', 'ForegroundColor', wht,...                 
                 'string','Diameter','BackgroundColor',nex_blu,'callback',{@pb_call,S}); 
S.mm_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(2)+btn_w-2*arr_w flooring(7.45,'fl') arr_w*3 flb_h],...
                 'FontUnits','normalized','FontWeight','bold', 'ForegroundColor', wht,...                 
                 'string','mm','BackgroundColor',nex_blu,'callback',{@pb_call,S});
S.currentstep_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(3) flooring(6.8,'fl') btn_w flb_h],...
                 'FontUnits','normalized','FontWeight','bold','ForegroundColor', wht,...                 
                 'string','Current Step','BackgroundColor',nex_blu,'callback',{@pb_call,S});
S.step_param_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(2) flooring(6,'fl')+jc btn_w flb_h],...
                 'FontUnits','normalized','FontWeight','bold', 'FontSize', 0.5,'ForegroundColor', wht,...                 
                 'string','Step Parameters','BackgroundColor',nex_blu,'callback',{@pb_call,S});
S.volume_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(2) flooring(5.5,'fl')+jc btn_w-3.5*arr_w flb_h],...
                 'FontUnits','normalized','FontWeight','bold','ForegroundColor', wht,...                 
                 'string','Volume','BackgroundColor',nex_blu,'callback',{@pb_call,S});
S.ml_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(2)+btn_w/1.5 flooring(5.5,'fl')+jc arr_w*3 flb_h],...
                 'FontUnits','normalized','FontWeight','bold', 'ForegroundColor', wht,...                 
                 'string','ml','BackgroundColor',nex_blu,'callback',{@pb_call,S});
S.rate_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(2) flooring(5.1,'fl')+jc btn_w-3.5*arr_w flb_h],...
                 'FontUnits','normalized','FontWeight','bold','ForegroundColor', wht,...                 
                 'string','Rate','BackgroundColor',nex_blu,'callback',{@pb_call,S});
S.ml_min_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(2)+btn_w/1.4 flooring(5.1,'fl')+jc arr_w*3 flb_h],...
                 'FontUnits','normalized','FontWeight','bold', 'ForegroundColor', wht,...                 
                 'string','ml/min','BackgroundColor',nex_blu,'callback',{@pb_call,S});
S.delay_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(2) flooring(3.4,'fl')+j2c-.015 btn_w/3 flb_h],...
                 'FontUnits','normalized','FontWeight','bold','ForegroundColor', wht,...                 
                 'string','Delay','BackgroundColor',nex_blu,'callback',{@pb_call,S});
S.delay_min_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(2)+btn_w/4 flooring(2.9,'fl')+j2c arr_w*3 flb_h],...
                 'FontUnits','normalized','FontWeight','bold', 'ForegroundColor', wht,...                 
                 'string','min','BackgroundColor',nex_blu,'callback',{@pb_call,S});
S.delay_sec_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(2)+btn_w-2*arr_w flooring(2.9,'fl')+j2c arr_w*3 flb_h],...
                 'FontUnits','normalized','FontWeight','bold', 'ForegroundColor', wht,...                 
                 'string','sec','BackgroundColor',nex_blu,'callback',{@pb_call,S});
S.time_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(2) flooring(2.4,'fl')+j2c-.015 btn_w/3 flb_h],...
                 'FontUnits','normalized','FontWeight','bold','ForegroundColor', wht,...                 
                 'string','Time','BackgroundColor',nex_blu,'callback',{@pb_call,S});
S.time_min_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(2)+btn_w/4 flooring(1.9,'fl')+j2c arr_w*3 flb_h],...
                 'FontUnits','normalized','FontWeight','bold', 'ForegroundColor', wht,...                 
                 'string','min','BackgroundColor',nex_blu,'callback',{@pb_call,S});
S.time_sec_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(2)+btn_w-2*arr_w flooring(1.9,'fl')+j2c arr_w*3 flb_h],...
                 'FontUnits','normalized','FontWeight','bold', 'ForegroundColor', wht,...                 
                 'string','sec','BackgroundColor',nex_blu,'callback',{@pb_call,S});
%Pump Status
S.pump_status_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(4) flooring(8.5,'fl') btn_w flb_h],...
                 'FontUnits','normalized','FontWeight','bold', 'FontSize', 0.7,'ForegroundColor', wht,...                 
                 'string','Pump Status','BackgroundColor',nex_blu,'callback',{@pb_call,S});
S.Connection_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(4) flooring(8,'fl') btn_w/2 flb_h],...
                 'FontUnits','normalized','FontWeight','bold','ForegroundColor', wht,...                 
                 'string','Connection','BackgroundColor',nex_blu,'callback',{@pb_call,S});
S.connect_sym = uicontrol(S.Nexus,'style', 'text', 'units', 'normalized',...
                'position', [coln(4)+btn_w*3/4 flooring(8.05, 'tp') arr_w*1.7 flb_h],...
                'FontUnits', 'normalized', 'FontWeight', 'bold', 'ForegroundColor',clr*0.7,...
                'string', char(9679), 'BackgroundColor',nex_blu, 'callback', {@pb_call, S});
S.status_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(4) flooring(7,'fl') btn_w flb_h],...
                 'FontUnits','normalized','FontWeight','normal','ForegroundColor', wht,...                 
                 'string','Status','BackgroundColor',nex_blu,'callback',{@pb_call,S});
S.Disp_vol_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(4) flooring(6,'fl') btn_w flb_h],...
                 'FontUnits','normalized','FontWeight','normal','ForegroundColor', wht,...                 
                 'string','Dispensed Volume','BackgroundColor',nex_blu,'callback',{@pb_call,S});
S.elapsed_time_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(4) flooring(5,'fl') btn_w flb_h],...
                 'FontUnits','normalized','FontWeight','normal', 'ForegroundColor', wht,...                 
                 'string','Elapsed Time','BackgroundColor',nex_blu,'callback',{@pb_call,S});
S.limits_label = uicontrol(S.Nexus, 'style','text','units','normalized',...
                 'position',[coln(4) flooring(4,'fl') btn_w flb_h],...
                 'FontUnits','normalized','FontWeight','normal','ForegroundColor', wht,...                 
                 'string','Limits','BackgroundColor',nex_blu,'callback',{@pb_call,S});
%% Borders
S.bor_limit1 =   uicontrol(S.Nexus,'style','text','units','normalized',...
                 'position',[coln(4) flooring(3.6,'b') bor_w bor_h],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'string',' ','BackgroundColor',lit_blu,'callback',{@pb_call,S});
S.bor_limit2 = uicontrol(S.Nexus,'style','text','units','normalized',...
                 'position',[coln(4) flooring(3.2,'b') bor_w bor_h],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'string',' ','BackgroundColor',lit_blu,'callback',{@pb_call,S});
S.bor_limit3 = uicontrol(S.Nexus,'style','text','units','normalized',...
                 'position',[coln(4) flooring(2.8,'b') bor_w bor_h],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'string',' ','BackgroundColor',lit_blu,'callback',{@pb_call,S});
S.bor_limit4 = uicontrol(S.Nexus,'style','text','units','normalized',...
                 'position',[coln(4) flooring(2.4,'b') bor_w bor_h],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'string',' ','BackgroundColor',lit_blu,'callback',{@pb_call,S});
%% Drop down menus
%Communication Settings       
S.port_io = uicontrol(S.Nexus,'style','pop','units','normalized',...
                   'position',[coln(1)+(3*arr_w) flooring(3, 'fl') btn_w-(3*arr_w) flb_h],...
                   'string',{'COM1',...
                            'COM2',...
                            'COM3',...
                            'COM4',...
                            'COM5',...
                            'COM6',...
                            'COM7',...
                            'COM8',...
                            'Refresh'},...
                   'FontUnits','normalized');

S.baud = uicontrol(S.Nexus,'style','pop','units','normalized',...
                   'position',[coln(1)+(3*arr_w) flooring(2.5, 'fl') btn_w-(3*arr_w) flb_h],...
                   'string',{'9600',...
                            '38400'},...
                   'FontUnits','normalized');
%Multi-Steps               
S.unit_enter = uicontrol(S.Nexus,'style','pop','units','normalized',...
                 'position',[coln(2)+(3*arr_w) flooring(8, 'fl') btn_w-(3*arr_w) flb_h],...
                 'string',{'ml/min',...
                           'ml/hr',...
                           'ul/min',...
                           'ul/hr'},...
                 'FontUnits','normalized','Tag','Nexus_Units','Callback',{@pop_call,S});
             
%% Push Buttons 
%(Start, Stop, Pause, Reset)
S.play = uicontrol(S.Nexus,'style', 'text', 'units', 'normalized',...
                'position', [coln(1) flooring(7.79, 'tp') arr_w*1.7 flb_h*1.3],...
                'FontUnits', 'normalized', 'FontWeight', 'bold', 'ForegroundColor',clr*0.7,'FontSize', 1,...
                'string', char(9654), 'BackgroundColor', nex_blu, 'callback', {@pb_call, S});
S.pb_start = uicontrol(S.Nexus,'style','push','units','normalized',...
                 'position',[coln(1)+btn_w*0.25 flooring(7.5,'b') btn_w*0.75 btn_h],...
                 'FontUnits','normalized','FontWeight','bold','ForegroundColor',blk,...                 
                 'string', 'Start','BackgroundColor',clr*0.7,'callback',{@pb_call,S});
S.stop_sq = uicontrol(S.Nexus,'style', 'text', 'units', 'normalized',...
                'position', [coln(1) flooring(6.7, 'tp') arr_w*1.7 flb_h*1.3],...
                'FontUnits', 'normalized', 'FontWeight', 'bold', 'ForegroundColor',clr*0.7,'FontSize', 0.7,...
                'string', char(9632), 'BackgroundColor',nex_blu, 'callback', {@pb_call, S});
S.pb_stop = uicontrol(S.Nexus,'style','push','units','normalized',...
                 'position',[coln(1)+btn_w*0.25 flooring(6.5,'b') btn_w*0.75 btn_h],...
                 'FontUnits','normalized','FontWeight','bold','ForegroundColor',blk,...                 
                 'string','Stop','BackgroundColor',clr*0.7,'callback',{@pb_call,S});
S.pause_sym = uicontrol(S.Nexus,'style', 'text', 'units', 'normalized',...
                'position', [coln(1) flooring(5.85, 'tp') arr_w*1.7 flb_h],...
                'FontUnits', 'normalized', 'FontWeight', 'bold', 'ForegroundColor',clr*0.7,'FontSize', 1.5,...
                'string', char(8214), 'BackgroundColor', nex_blu, 'callback', {@pb_call, S});
S.pb_pause = uicontrol(S.Nexus,'style','push','units','normalized',...
                 'position',[coln(1)+btn_w*0.25 flooring(5.5,'b') btn_w*0.75 btn_h],...
                 'FontUnits','normalized','FontWeight','bold','ForegroundColor',blk,...                 
                 'string','Pause','BackgroundColor',clr*0.7,'callback',{@pb_call,S});
S.reset_sym = uicontrol(S.Nexus,'style', 'text', 'units', 'normalized',...
                'position', [coln(1) flooring(4.85, 'tp') arr_w*1.7 flb_h],...
                'FontUnits', 'normalized', 'FontWeight', 'bold', 'ForegroundColor',clr*0.7,'FontSize', 1,...
                'string', char(8635), 'BackgroundColor', nex_blu, 'callback', {@pb_call, S});
S.pb_reset = uicontrol(S.Nexus,'style','push','units','normalized',...
                 'position',[coln(1)+btn_w*0.25 flooring(4.5,'b') btn_w*0.75 btn_h],...
                 'FontUnits','normalized','FontWeight','bold','ForegroundColor',blk,...                 
                 'string','Reset','BackgroundColor',clr*0.7,'callback',{@pb_call,S});
%% Changeable rates
S.diam_enter = uicontrol(S.Nexus,'style','edit','units','normalized',...
                 'position',[coln(2)+3*arr_w flooring(7.5,'fl')+.015 btn_w-4.3*arr_w flb_h-.015],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'string','10','BackgroundColor',wht,'callback',{@edit_call,S});
% Step Parameters
S.volume_enter = uicontrol(S.Nexus,'style','edit','units','normalized',...
                 'position',[coln(2)+2.8*arr_w flooring(5.7,'fl')+jc btn_w-4.3*arr_w flb_h-.015],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'string','0','BackgroundColor',wht,'callback',{@edit_call,S});
S.rate_enter = uicontrol(S.Nexus,'style','edit','units','normalized',...
                 'position',[coln(2)+2.8*arr_w flooring(5.3,'fl')+jc btn_w-4.3*arr_w flb_h-.015],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'string','0','BackgroundColor',wht,'callback',{@edit_call,S});
S.delay_min_enter = uicontrol(S.Nexus,'style','edit','units','normalized',...
                 'position',[coln(2)+0.03 flooring(3.07,'fl')+j2c btn_w/4 flb_h-.015],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'string','0','BackgroundColor',wht,'callback',{@edit_call,S});
S.delay_sec_enter = uicontrol(S.Nexus,'style','edit','units','normalized',...
                 'position',[coln(2)+0.13 flooring(3.07,'fl')+j2c btn_w/4 flb_h-.015],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'string','0','BackgroundColor',wht,'callback',{@edit_call,S});
S.time_min_enter = uicontrol(S.Nexus,'style','edit','units','normalized',...
                 'position',[coln(2)+0.03 flooring(2.07,'fl')+j2c btn_w/4 flb_h-.015],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'string','0','BackgroundColor',wht,'callback',{@edit_call,S});
S.time_sec_enter = uicontrol(S.Nexus,'style','edit','units','normalized',...
                 'position',[coln(2)+0.13 flooring(2.07,'fl')+j2c btn_w/4 flb_h-.015],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'string','0','BackgroundColor',wht,'callback',{@edit_call,S});
%% Status
S.Lstatus = uicontrol(S.Nexus,'style','text','units','normalized',...
                 'position',[coln(4)+0.005 flooring(6.7,'b') btn_w lbl_h],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'string',' ','BackgroundColor',edit_clr,'callback',{@pb_call,S});
S.Lstat_disp_vol = uicontrol(S.Nexus,'style','text','units','normalized',...
                 'position',[coln(4)+0.005 flooring(5.7,'b') btn_w lbl_h],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'string',' ','BackgroundColor',edit_clr,'callback',{@pb_call,S});
S.Lstat_elapse_time = uicontrol(S.Nexus,'style','text','units','normalized',...
                 'position',[coln(4)+0.005 flooring(4.7,'b') btn_w lbl_h],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'string',' ','BackgroundColor',edit_clr,'callback',{@pb_call,S});
S.Lstat_limit1 = uicontrol(S.Nexus,'style','text','units','normalized',...
                 'position',[coln(4)+0.005 flooring(3.65,'b') btn_w lbl_h-0.01],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'string',' ','BackgroundColor',edit_clr,'callback',{@pb_call,S});
S.Lstat_limit2 = uicontrol(S.Nexus,'style','text','units','normalized',...
                 'position',[coln(4)+0.005 flooring(3.26,'b') btn_w lbl_h-0.01],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'string',' ','BackgroundColor',edit_clr,'callback',{@pb_call,S});
S.Lstat_limit3 = uicontrol(S.Nexus,'style','text','units','normalized',...
                 'position',[coln(4)+0.005 flooring(2.8635,'b') btn_w lbl_h-0.01],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'string',' ','BackgroundColor',edit_clr,'callback',{@pb_call,S});
S.Lstat_limit4 = uicontrol(S.Nexus,'style','text','units','normalized',...
                 'position',[coln(4)+0.005 flooring(2.476,'b') btn_w lbl_h-0.01],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'string',' ','BackgroundColor',edit_clr,'callback',{@pb_call,S});            

%% Step Parameters (Linked List)
max_number_of_steps = 30; %pre-defined limit: it is better to predefine a limit too high than to make a true dynamic array (unlike in C or C++)
if ~isfield(S,'n')
    data = struct('Name',strcat('Step',{' '},'0'),...
                  'Volume',0,'Volume_U','ml',...
                  'Rate'  ,0,'Rate_U'  ,'ml/min',...
                  'Delay_min',0,'Delay_sec',0,...
                  'Time_min' ,0,'Time_sec' ,0);
    S.n = repmat(data,1,max_number_of_steps); %copy struct 3000 times into a struct array
    for i = 1:4 %4 being default number of steps
        S.n(1,i).Name = strcat('Step',{' '},num2str(i)); %Name first four cells
    end
end
S.currentstep_enter = uicontrol(S.Nexus,'style','pop','units','normalized',...
                 'position',[coln(3)+0.1*jc flooring(6.5, 'fl') btn_w-0.1*jc flb_h],...
                 'string',{'Step 1',...
                           'Step 2',...
                           'Step 3',...
                           'Step 4'},...
                 'FontUnits','normalized','Tag','Nexus_Step','Callback',{@pop_call,S});
%Multi-Steps
S.pb_sendsteps = uicontrol(S.Nexus,'style','push','units','normalized',...
                 'position',[coln(3)+0.1*jc flooring(7.6,'b') btn_w-0.1*jc btn_h],...
                 'FontUnits','normalized','FontWeight','bold','ForegroundColor',blk,...                 
                 'string','Send Steps','BackgroundColor',clr*0.7,'callback',{@pb_call,S});
S.pb_apply_param = uicontrol(S.Nexus,'style','push','units','normalized',...
                 'position',[coln(3)+0.1*jc flooring(5.5,'b') btn_w-0.1*jc btn_h],...
                 'FontUnits','normalized','FontWeight','bold','ForegroundColor',blk,...                 
                 'string','Apply Parameters','BackgroundColor',clr*0.7,'callback',{@pb_call,S});
S.pb_add_step_before = uicontrol(S.Nexus,'style','push','units','normalized',...
                 'position',[coln(3)+0.1*jc flooring(4.5,'b') btn_w-0.1*jc btn_h],...
                 'FontUnits','normalized','FontWeight','bold','ForegroundColor',blk,...                 
                 'string','Add Step Before','BackgroundColor',clr*0.7,'callback',{@pb_call,S});
S.pb_add_step_after = uicontrol(S.Nexus,'style','push','units','normalized',...
                 'position',[coln(3)+0.1*jc flooring(3.5,'b') btn_w-0.1*jc btn_h],...
                 'FontUnits','normalized','FontWeight','bold','ForegroundColor',blk,...                 
                 'string','Add Step After','BackgroundColor',clr*0.7,'callback',{@pb_call,S});
S.pb_remove_step = uicontrol(S.Nexus,'style','push','units','normalized',...
                 'position',[coln(3)+0.1*jc flooring(2.5,'b') btn_w-0.1*jc btn_h],...
                 'FontUnits','normalized','FontWeight','bold','ForegroundColor',blk,...                 
                 'string','Remove Step','BackgroundColor',clr*0.7,'callback',{@pb_call,S});
end
