# Multi-Pump-Interface
function S = LittleThingsFactory_MrQ_panel_setup(varargin)

% Parent - PanelSet.m
% Additions - S.MrQ 
% Description - Creates Chemyx MrQ panel and all of the
%               functions and interfaces associated with
%               this particular pump
S = varargin{1};
K = varargin{2};
%% Deconstruction
btn_w = S.panel_struct.btn_w;
btn_h = S.panel_struct.btn_h;
lbl_h = S.panel_struct.lbl_h;
flb_h = S.panel_struct.flb_h;
arr_w = S.panel_struct.arr_w;
panel_w = S.panel_struct.panel_w;
clr = S.panel_struct.clr;
edit_clr = S.panel_struct.edit_clr;
panpos = S.panel_struct.panpos;
coln = S.panel_struct.coln;
Max = S.panel_struct.Max;
Min = S.panel_struct.Min;
red = S.color.red;
blu = S.color.blu;
q_blu = S.color.q_blu;
grn = S.color.grn;
ppl = S.color.ppl;
org = S.color.org;
wht = S.color.wht;
blk = S.color.blk;
gry = S.color.gry;
grey = S.color.grey;
lit_red = S.color.lit_red;
lit_blu = S.color.lit_blu;
lit_grn = S.color.lit_grn;
lit_ppl = S.color.lit_ppl;
lite_ppl = S.color.lite_ppl;
lit_org = S.color.lit_org;

%% MrQ Panel
S.MrQ = uipanel(K,'BorderType','none','BackgroundColor',clr,'Visible','off','Position',panpos,'Tag',strcat('MrQ_', num2str(K.UserData)));

%% %%%%%%%%%%%%%%%%%%%%%%% Pump figures go here
%% Channel Control
S.column1 = uipanel(S.MrQ,'Visible','on','position',[0 0 panel_w/2 1],'BackgroundColor',q_blu,'BorderType','none');%'etchedout');             
S.column2 = uipanel(S.MrQ,'Visible','on','position',[panel_w/2+0.01 0 panel_w/2-0.01 1],'BackgroundColor',q_blu,'BorderType','none');%'etchedout');             
S.column3 = uipanel(S.MrQ,'Visible','on','position',[panel_w+0.01 0 panel_w 1],'BackgroundColor',q_blu,'BorderType','none');%'etchedout');  

%% Pump 1
S.SetPump1 = uicontrol(S.MrQ, 'style','text','units','normalized',...
                 'position',[coln(1) flooring(8,'fl') btn_w btn_h],...
                 'FontUnits','normalized','FontWeight','bold', 'ForegroundColor', wht, 'FontSize', 0.4,...                 
                 'string','Pump 1 Settings','BackgroundColor',q_blu,'callback',{@pb_call,S});
S.rate1 = uicontrol(S.MrQ, 'style', 'text', 'units', 'normalized',...
                 'position', [coln(1) flooring(7, 'fl') btn_w btn_h],...
                 'FontUnits', 'normalized', 'FontWeight', 'normal', 'ForegroundColor', wht, 'FontSize', 0.3,...
                 'string', 'Rate', 'BackgroundColor', q_blu, 'callback', {@pb_call, S});
S.injtype1 = uicontrol(S.MrQ, 'style', 'text', 'units', 'normalized',...
                 'position', [coln(1) flooring(6, 'fl') btn_w btn_h],...
                 'FontUnits', 'normalized', 'FontWeight', 'normal', 'ForegroundColor', wht, 'FontSize', 0.3,...
                 'string', 'Injection Type', 'BackgroundColor', q_blu, 'callback', {@pb_call, S});
S.selection_panel_1 = uipanel(S.MrQ, 'Visible','on','position',[0 0.3 panel_w/2 0.25],'BackgroundColor',grey,'BorderType','none');
S.flow1_title = uicontrol(S.MrQ, 'style', 'text', 'units', 'normalized',...
                 'position', [coln(1) flooring(5.35, 'fl') btn_w lbl_h],...
                 'FontUnits', 'normalized', 'FontWeight', 'normal', 'ForegroundColor', blk,...
                 'string', 'Flow Rate (ul/min)', 'BackgroundColor', grey, 'callback', {@pb_call, S});
S.checkbox_flow1 = uicontrol(S.MrQ,'style','checkbox', 'units', 'normalized', ...
                'String', 'Flow Rate (ul/min)','position', [coln(1) flooring(5.6, 'tp') 0.03 0.03],...
                'FontUnits', 'normalized', 'FontWeight', 'bold', 'ForegroundColor',clr*0.7,'FontSize', 1,...
               'BackgroundColor', grey,'callback', {@pb_call, S});
S.autostart1_title = uicontrol(S.MrQ, 'style', 'text', 'units', 'normalized',...
                 'position', [coln(1)-0.01 flooring(5, 'fl') btn_w lbl_h],...
                 'FontUnits', 'normalized', 'FontWeight', 'normal', 'ForegroundColor', blk,...
                 'string', 'Automatic Start', 'BackgroundColor', grey, 'callback', {@pb_call, S});
S.checkbox_autostart1 = uicontrol(S.MrQ, 'style', 'checkbox', 'units', 'normalized',...
                'String', 'Automatic Start','position', [coln(1) flooring(5.2, 'tp') 0.03 0.03],...
                'FontUnits', 'normalized', 'FontWeight', 'bold', 'ForegroundColor',clr*0.7,'FontSize', 1,...
                'BackgroundColor', grey, 'callback', {@pb_call, S});
% %% Selection Buttons
% operation_type_1 = uibuttongroup(S.MrQ, 'Title', 'Operation Type', 'position', [0 0.3 panel_w/2 0.15]);
% uicontrol('Parent',operation_type_1, 'Style', 'radiobutton',...
%                    'String', 'invisible',...
%                    'position', [0 0 0 0], 'Tag', 'invisibutton');
%           
% uicontrol('Parent',operation_type_1,'Style','radiobutton',...
%                    'String', 'Time Operation',...
%                    'Position', 100*[0.1 flooring(3.5, 'tp') 1.2 0.15], 'Tag', 'timeop1',...
%                    'callback', {@pb_call, S});
%              
% uicontrol('Parent',operation_type_1,'Style','radiobutton',...
%                    'String', 'Volume Operation',...
%                    'Position', 100*[0.1 flooring(2.5, 'tp') 1.2 0.15], 'Tag', 'volumeop1',...
%                    'callback', {@pb_call, S});

%set(handles.volumeop1, 'SelectionChangeFcn', @volumeop1_SelectionChangeFcn);               
% S.result_panel_time1 = uipanel('Parent',S.MrQ,'position',[0 0.01 panel_w/2 0.25],'BackgroundColor',clr*0.7,'BorderType','none');
% if timeop1.Value
%     S.result_panel_time1.Visible = 'On';
% else
%     S.result_panel_time1.Visible = 'Off'; 
% end
% S.result_panel_volume1 = uipanel('Parent',S.MrQ,'position',[0 0.01 panel_w/2 0.25],'BackgroundColor',clr*0.7,'BorderType','none');
% if volumeop1.Value
%     S.result_panel_volume1.Visible = 'On';
% else
%     S.result_panel_volume1.Visible = 'Off';
% end
%% Volume panel 1
S.result_panel_volume1 = uipanel('Parent',S.MrQ,'Visible','off','position',[0 0.01 panel_w/2 0.25],'BackgroundColor',clr*0.7,'BorderType','none');
S.result_panel_volume = uicontrol('style', 'text', 'units', 'normalized','Parent', S.result_panel_volume1,...
                'position', [0 flooring(6.7, 'tp') btn_w*4.3 lbl_h*5], ...
                'FontUnits', 'normalized', 'FontWeight', 'normal', 'ForegroundColor',wht, 'FontSize', 0.6,...
                'Visible', S.result_panel_volume1.Visible, 'String', 'Desired Volume:', 'BackgroundColor', clr*0.7, 'callback', {@pb_call, S});
S.result_panel_ml = uicontrol('style', 'text', 'units', 'normalized','Parent', S.result_panel_volume1,...
                'position', [0.65 flooring(4, 'tp') btn_w lbl_h*4],...
                'FontUnits', 'normalized', 'FontWeight', 'bold', 'ForegroundColor',blk,...
                'Visible', S.result_panel_volume1.Visible,'String', 'ml', 'BackgroundColor', clr*0.7, 'callback', {@pb_call, S});
S.volume_enter = uicontrol('style','edit','units','normalized','Parent', S.result_panel_volume1,...
                 'position',[0.1 flooring(4,'fl') btn_w*2.5 flb_h*4],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'Visible', S.result_panel_volume1.Visible,'string','10','BackgroundColor',wht,'callback',{@edit_call,S});
% S.checkbox_volume1 = uiradiobutton(S.selection_panel_1, ...
%                 'Text', 'Volume Operation','position', [coln(1) flooring(4.2, 'tp') 0.03 0.03],...
%                 'FontUnits', 'normalized', 'FontWeight', 'bold', 'ForegroundColor',clr*0.7,'FontSize', 1,...
%                 'Enable', 'On', 'String', 'checkvol1','BackgroundColor', clr*0.7);
% 'callback', {@pb_call, S});
%% Time panel 1
%     function timeop_SelectionChangeFcn(hObject, eventdata)
%         handles = guidata(hObject);
%         switch get(eventdata.Newvalue, 'Tag')
%             case 'timeop1'
%                 handles.value = 1;
%             case 'volumeop1'
%                 handles.value = -1;
S.result_panel_time1 = uipanel('Parent',S.MrQ,'Visible','off','position',[0 0.01 panel_w/2 0.25],'BackgroundColor',clr*0.7,'BorderType','none');
S.result_panel_time = uicontrol('style', 'text', 'units', 'normalized','Parent', S.result_panel_time1,...
                'position', [0 flooring(6.7, 'tp') btn_w*4.3 lbl_h*5], ...
                'FontUnits', 'normalized', 'FontWeight', 'normal', 'ForegroundColor',wht, 'FontSize', 0.4,...
                'Visible', S.result_panel_time1.Visible, 'String', 'Select Date and Time:', 'BackgroundColor', clr*0.7, 'callback', {@pb_call, S});
S.cal_dateTextHandle1 = uicontrol('Style', 'Text', 'units', 'normalized', 'Parent', S.result_panel_time1,...
                'String', 'Date:', 'BackgroundColor', clr*0.7,...
                'FontUnits', 'normalized', 'FontWeight', 'normal', 'FontSize', 0.9,...
                'Position', [0.0 flooring(6, 'fl') btn_w flb_h*2], 'callback', {@pb_call, S});
S.cal_dateEditBoxHandle1 = uicontrol('Style', 'Edit', 'units', 'normalized', 'Parent', S.result_panel_time1,...
                'Position', [0.22 flooring(5.7, 'fl') btn_w*2.3 flb_h*3],...
                'BackgroundColor', edit_clr, 'callback', {@pb_call, S});
[x,map] = imread('small cal.jpg');
cal = imresize(x, 0.6);
S.calendarButtonHandle1 = uicontrol('Style', 'PushButton', 'units', 'normalized', 'Parent', S.result_panel_time1,...
                'Position', [0.77 flooring(5.5, 'fl') btn_w flb_h*4],...
                'cdata', cal, ...
                'callback', @pushbutton_cb);
    function pushbutton_cb(U, eventStruct)
            uicalendar('Weekend', [1 0 0 0 0 0 1],...
                'SelectionType', 1,...
                'DestinationUI',S.cal_dateEditBoxHandle1);
    end
S.time_title1 = uicontrol('Style', 'Text', 'units', 'normalized', 'Parent', S.result_panel_time1,...
                'String', 'Time:', 'BackgroundColor', clr*0.7,...
                'FontUnits', 'normalized', 'FontWeight', 'normal', 'FontSize', 0.9,...
                'Position', [0.0 flooring(3.4, 'fl') btn_w flb_h*2], 'callback', {@pb_call, S});
S.colon1_1 = uicontrol('Style', 'Text', 'units', 'normalized', 'Parent', S.result_panel_time1,...
                'String', ':', 'BackgroundColor', clr*0.7,...
                'FontUnits', 'normalized', 'FontWeight', 'bold', 'FontSize', 0.9,...
                'Position', [0.285 flooring(3.4, 'fl') btn_w flb_h*2], 'callback', {@pb_call, S});
S.hour_enter1 = uicontrol('style','edit','units','normalized','Parent', S.result_panel_time1,...
                 'position',[0.22 flooring(3,'fl') btn_w*0.7 flb_h*3],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'Visible', S.result_panel_time1.Visible,'string','HH','BackgroundColor',edit_clr,'callback',{@edit_call,S});
S.colon2_1 = uicontrol('Style', 'Text', 'units', 'normalized', 'Parent', S.result_panel_time1,...
                'String', ':', 'BackgroundColor', clr*0.7,...
                'FontUnits', 'normalized', 'FontWeight', 'bold', 'FontSize', 0.9,...
                'Position', [0.47 flooring(3.4, 'fl') btn_w flb_h*2], 'callback', {@pb_call, S});
S.min_enter1 = uicontrol('style','edit','units','normalized','Parent', S.result_panel_time1,...
                 'position',[0.405 flooring(3,'fl') btn_w*0.7 flb_h*3],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'Visible', S.result_panel_time1.Visible,'string','MM','BackgroundColor',edit_clr,'callback',{@edit_call,S});
S.sec_enter1 = uicontrol('style','edit','units','normalized','Parent', S.result_panel_time1,...
                 'position',[0.588 flooring(3,'fl') btn_w*0.7 flb_h*3],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'Visible', S.result_panel_time1.Visible,'string','SS','BackgroundColor',edit_clr,'callback',{@edit_call,S});
S.AM_PM1 = uicontrol('style','pop','units','normalized', 'Parent', S.result_panel_time1,...
                   'BackgroundColor', edit_clr, 'FontWeight', 'bold',...
                   'position',[0.75 flooring(3.15, 'fl') btn_w*1.2 flb_h*3],...
                   'string',{'AM',...
                            'PM'},...
                   'FontUnits','normalized', 'Visible', S.result_panel_time1.Visible, 'callback', {@edit_call, S});
%Checkbox for time (Pump 1)
% S.checkbox_timeop1 = radiobutton(S.selection_panel_1, ...
%                 'position', [coln(1) flooring(4.6, 'tp') 0.03 0.03],...
%                 'FontUnits', 'normalized', 'FontWeight', 'bold', 'ForegroundColor',clr*0.7,'FontSize', 1,...
%                 'Enable', 'On', 'string', 'checktime1', 'BackgroundColor', clr*0.7);
% 'callback', {@pb_call, S});
%% Selection Buttons
operation_type_1 = uibuttongroup(S.MrQ, 'Title', 'Operation Type', 'position', [0 0.3 panel_w/2 0.15]);
uicontrol('Parent',operation_type_1, 'Style', 'radiobutton',...
                   'String', 'invisible',...
                   'position', [0 0 0 0], 'Tag', 'invisibutton');
          
uicontrol('Parent',operation_type_1,'Style','radiobutton',...
                   'String', 'Time Operation 1',...
                   'Position', 100*[0.1 flooring(3.5, 'tp') 1.2 0.15], 'Tag', 'timeop1',...
                   'callback', {@pb_call, S});
             
uicontrol('Parent',operation_type_1,'Style','radiobutton',...
                   'String', 'Volume Operation 1',...
                   'Position', 100*[0.1 flooring(2.5, 'tp') 1.2 0.15], 'Tag', 'volumeop1',...
                   'callback', {@pb_call, S});
%% Pump 2
S.SetPump2 = uicontrol(S.MrQ, 'style','text','units','normalized',...
                 'position',[coln(2) flooring(8,'fl') btn_w btn_h],...
                 'FontUnits','normalized','FontWeight','bold', 'ForegroundColor', wht, 'FontSize', 0.4,...                 
                 'string','Pump 2 Settings','BackgroundColor',q_blu,'callback',{@pb_call,S});
S.rate2 = uicontrol(S.MrQ, 'style', 'text', 'units', 'normalized',...
                 'position', [coln(2) flooring(7, 'fl') btn_w btn_h],...
                 'FontUnits', 'normalized', 'FontWeight', 'normal', 'ForegroundColor', wht, 'FontSize', 0.3,...
                 'string', 'Rate', 'BackgroundColor', q_blu, 'callback', {@pb_call, S});
S.injtype2 = uicontrol(S.MrQ, 'style', 'text', 'units', 'normalized',...
                 'position', [coln(2) flooring(6, 'fl') btn_w btn_h],...
                 'FontUnits', 'normalized', 'FontWeight', 'normal', 'ForegroundColor', wht, 'FontSize', 0.3,...
                 'string', 'Injection Type', 'BackgroundColor', q_blu, 'callback', {@pb_call, S});
S.selection_panel_2 = uipanel(S.MrQ,'Visible','on','position',[panel_w/2+0.01 0.3 panel_w/2-0.01 0.25],'BackgroundColor',clr*0.7,'BorderType','none');
S.flow2_title = uicontrol(S.MrQ, 'style', 'text', 'units', 'normalized',...
                 'position', [coln(2)+0.02 flooring(5.35, 'fl') btn_w-arr_w lbl_h],...
                 'FontUnits', 'normalized', 'FontWeight', 'normal', 'ForegroundColor', wht,...
                 'string', 'Flow Rate (ul/min)', 'BackgroundColor', clr*0.7, 'callback', {@pb_call, S});
S.checkbox_flow2 = uicontrol(S.MrQ,'style', 'checkbox', 'units', 'normalized',...
                'position', [coln(2)+0.01 flooring(5.6, 'tp') 0.03 0.03],...
                'FontUnits', 'normalized', 'FontWeight', 'bold', 'ForegroundColor',clr*0.7,'FontSize', 1,...
                'BackgroundColor', clr*0.7, 'callback', {@pb_call, S});
S.autostart2_title = uicontrol(S.MrQ, 'style', 'text', 'units', 'normalized',...
                 'position', [coln(2) flooring(5, 'fl') btn_w lbl_h],...
                 'FontUnits', 'normalized', 'FontWeight', 'normal', 'ForegroundColor', wht,...
                 'string', 'Automatic Start', 'BackgroundColor', clr*0.7, 'callback', {@pb_call, S});
S.checkbox_autostart2 = uicontrol(S.MrQ,'style', 'checkbox', 'units', 'normalized',...
                'position', [coln(2)+0.01 flooring(5.2, 'tp') 0.03 0.03],...
                'FontUnits', 'normalized', 'FontWeight', 'bold', 'ForegroundColor',clr*0.7,'FontSize', 1,...
                'BackgroundColor', clr*0.7, 'callback', {@pb_call, S});
S.optype2_title = uicontrol(S.MrQ, 'style', 'text', 'units', 'normalized',...
                 'position', [coln(2) flooring(4.7, 'fl') btn_w-arr_w lbl_h],...
                 'FontUnits', 'normalized', 'FontWeight', 'bold', 'ForegroundColor',blk,...
                 'string', 'Operation Type', 'BackgroundColor', clr*0.7, 'callback', {@pb_call, S});
S.timeop2_title = uicontrol(S.MrQ, 'style', 'text', 'units', 'normalized',...
                 'position', [coln(2) flooring(4.37, 'fl') btn_w lbl_h],...
                 'FontUnits', 'normalized', 'FontWeight', 'normal', 'ForegroundColor', wht,...
                 'string', 'Time Operation', 'BackgroundColor', clr*0.7, 'callback', {@pb_call, S});
% S.checkbox_timeop2 = uicontrol(S.MrQ,'style', 'checkbox', 'units', 'normalized',...
%                 'position', [coln(2)+0.01 flooring(4.6, 'tp') 0.03 0.03],...
%                 'FontUnits', 'normalized', 'FontWeight', 'bold', 'ForegroundColor',clr*0.7,'FontSize', 1,...
%                 'BackgroundColor', clr*0.7, 'callback', {@pb_call, S});
%% Volume panel 2
S.volumeop2_title = uicontrol(S.MrQ, 'style', 'text', 'units', 'normalized',...
                 'position', [coln(2) flooring(4.07, 'fl') btn_w lbl_h-0.01],...
                 'FontUnits', 'normalized', 'FontWeight', 'normal', 'ForegroundColor', wht,...
                 'string', 'Volume Operation', 'BackgroundColor', clr*0.7, 'callback', {@pb_call, S});
S.result_panel_volume2 = uipanel('Parent',S.MrQ,'Visible','off','position',[coln(2) 0.01 panel_w/2-0.01 0.25],'BackgroundColor',clr*0.7,'BorderType','none');
S.result_panel_vol2 = uicontrol(S.MrQ,'style', 'text', 'units', 'normalized','Parent', S.result_panel_volume2,...
                'position', [0 flooring(6.7, 'tp') btn_w*4.3 lbl_h*5], ...
                'FontUnits', 'normalized', 'FontWeight', 'normal', 'ForegroundColor',wht, 'FontSize', 0.6,...
                'Visible', S.result_panel_volume1.Visible, 'String', 'Desired Volume:', 'BackgroundColor', clr*0.7, 'callback', {@pb_call, S});
S.result_panel_ml2 = uicontrol(S.MrQ,'style', 'text', 'units', 'normalized','Parent', S.result_panel_volume2,...
                'position', [0.65 flooring(4, 'tp') btn_w lbl_h*4],...
                'FontUnits', 'normalized', 'FontWeight', 'bold', 'ForegroundColor',blk,...
                'Visible', S.result_panel_volume1.Visible,'String', 'ml', 'BackgroundColor', clr*0.7, 'callback', {@pb_call, S});
S.volume_enter2 = uicontrol(S.MrQ,'style','edit','units','normalized','Parent', S.result_panel_volume2,...
                 'position',[0.1 flooring(4,'fl') btn_w*2.5 flb_h*4],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'Visible', S.result_panel_volume1.Visible,'string','10','BackgroundColor',wht,'callback',{@edit_call,S});
%Volume 2 checkbox
S.checkbox_volume2 = uicontrol(S.MrQ,'style', 'checkbox', 'units', 'normalized',...
                'position', [coln(2)+0.01 flooring(4.2, 'tp') 0.03 0.03],...
                'FontUnits', 'normalized', 'FontWeight', 'bold', 'ForegroundColor',clr*0.7,'FontSize', 1,...
                'Enable', 'On', 'string', 'checkvol2', 'BackgroundColor', clr*0.7, 'callback', {@pb_call, S});
%% Time panel 2
S.result_panel_time2 = uipanel('Parent',S.MrQ,'Visible','off','position',[coln(2) 0.01 panel_w/2-0.01 0.25],'BackgroundColor',clr*0.7,'BorderType','none');
S.result_pan_time2 = uicontrol(S.MrQ,'style', 'text', 'units', 'normalized','Parent', S.result_panel_time2,...
                'position', [0 flooring(6.7, 'tp') btn_w*4.3 lbl_h*5], ...
                'FontUnits', 'normalized', 'FontWeight', 'normal', 'ForegroundColor',wht, 'FontSize', 0.4,...
                'Visible', S.result_panel_time2.Visible, 'String', 'Select Date and Time:', 'BackgroundColor', clr*0.7, 'callback', {@pb_call, S});
S.cal_dateTextHandle2 = uicontrol(S.MrQ, 'Style', 'Text', 'units', 'normalized', 'Parent', S.result_panel_time2,...
                'String', 'Date:', 'BackgroundColor', clr*0.7,...
                'FontUnits', 'normalized', 'FontWeight', 'normal', 'FontSize', 0.9,...
                'Position', [0 flooring(6, 'fl') btn_w flb_h*2], 'callback', {@pb_call, S});
S.cal_dateEditBoxHandle2 = uicontrol(S.MrQ, 'Style', 'Edit', 'units', 'normalized', 'Parent', S.result_panel_time2,...
                'Position', [0.22 flooring(5.7, 'fl') btn_w*2.3 flb_h*3],...
                'BackgroundColor', edit_clr, 'callback', {@pb_call, S});
[x,map] = imread('small cal.jpg');
cal = imresize(x, 0.6);
S.calendarButtonHandle2 = uicontrol(S.MrQ, 'Style', 'PushButton', 'units', 'normalized', 'Parent', S.result_panel_time2,...
                'Position', [0.77 flooring(5.5, 'fl') btn_w flb_h*4],...
                'cdata', cal, ...
                'callback', @pushbutton_cb2);
    function pushbutton_cb2(U, eventStruct)
            uicalendar('Weekend', [1 0 0 0 0 0 1],...
                'SelectionType', 1,...
                'DestinationUI',S.cal_dateEditBoxHandle2);
    end
S.time_title2 = uicontrol(S.MrQ, 'Style', 'Text', 'units', 'normalized', 'Parent', S.result_panel_time2,...
                'String', 'Time:', 'BackgroundColor', clr*0.7,...
                'FontUnits', 'normalized', 'FontWeight', 'normal', 'FontSize', 0.9,...
                'Position', [0 flooring(3.4, 'fl') btn_w flb_h*2], 'callback', {@pb_call, S});
S.colon1_2 = uicontrol(S.MrQ, 'Style', 'Text', 'units', 'normalized', 'Parent', S.result_panel_time2,...
                'String', ':', 'BackgroundColor', clr*0.7,...
                'FontUnits', 'normalized', 'FontWeight', 'bold', 'FontSize', 0.9,...
                'Position', [0.285 flooring(3.4, 'fl') btn_w flb_h*2], 'callback', {@pb_call, S});
S.hour_enter2 = uicontrol(S.MrQ,'style','edit','units','normalized','Parent', S.result_panel_time2,...
                 'position',[0.22 flooring(3,'fl') btn_w*0.7 flb_h*3],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'Visible', S.result_panel_time2.Visible,'string','HH','BackgroundColor',edit_clr,'callback',{@edit_call,S});
S.colon2_2 = uicontrol(S.MrQ, 'Style', 'Text', 'units', 'normalized', 'Parent', S.result_panel_time2,...
                'String', ':', 'BackgroundColor', clr*0.7,...
                'FontUnits', 'normalized', 'FontWeight', 'bold', 'FontSize', 0.9,...
                'Position', [0.47 flooring(3.4, 'fl') btn_w flb_h*2], 'callback', {@pb_call, S});
S.min_enter2 = uicontrol(S.MrQ,'style','edit','units','normalized','Parent', S.result_panel_time2,...
                 'position',[0.405 flooring(3,'fl') btn_w*0.7 flb_h*3],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'Visible', S.result_panel_time2.Visible,'string','MM','BackgroundColor',edit_clr,'callback',{@edit_call,S});
S.sec_enter2 = uicontrol(S.MrQ,'style','edit','units','normalized','Parent', S.result_panel_time2,...
                 'position',[0.588 flooring(3,'fl') btn_w*0.7 flb_h*3],...
                 'FontUnits','normalized','FontWeight','bold',...                 
                 'Visible', S.result_panel_time2.Visible,'string','SS','BackgroundColor',edit_clr,'callback',{@edit_call,S});
S.AM_PM2 = uicontrol(S.MrQ,'style','pop','units','normalized', 'Parent', S.result_panel_time2,...
                   'BackgroundColor', edit_clr, 'FontWeight', 'bold',...
                   'position',[0.755 flooring(3.15, 'fl') btn_w*1.25 flb_h*3],...
                   'string',{'AM',...
                            'PM'},...
                   'FontUnits','normalized', 'Visible', S.result_panel_time2.Visible, 'callback', {@edit_call, S});
% Time 2 checkbox
% S.checkbox_timeop2 = uicontrol(S.MrQ,'style', 'checkbox', 'units', 'normalized',...
%                 'position', [coln(2)+0.01 flooring(4.6, 'tp') 0.03 0.03],...
%                 'FontUnits', 'normalized', 'FontWeight', 'bold', 'ForegroundColor',clr*0.7,'FontSize', 1,...
%                 'Enable', 'On', 'string', 'checktime2', 'BackgroundColor', clr*0.7, 'callback', {@pb_call, S});
% S.result_panel_2 = uipanel(S.MrQ,'visible','off','position',[panel_w/2+0.01 0.01 panel_w/2-0.01 0.25],'BackgroundColor',clr*0.7,'BorderType','none');

%% Selection Buttons 2
operation_type_2 = uibuttongroup(S.MrQ, 'Title', 'Operation Type', 'position', [panel_w/2+0.01 0.3 panel_w/2-0.01 0.15]);
uicontrol('Parent',operation_type_2, 'Style', 'radiobutton',...
                   'String', 'invisible',...
                   'position', [0 0 0 0], 'Tag', 'invisibutton');
          
uicontrol('Parent',operation_type_2,'Style','radiobutton',...
                   'String', 'Time Operation 2',...
                   'Position', 100*[0.1 flooring(3.5, 'tp') 1.2 0.15], 'Tag', 'timeop1',...
                   'callback', {@pb_call, S});
             
uicontrol('Parent',operation_type_2,'Style','radiobutton',...
                   'String', 'Volume Operation 2',...
                   'Position', 100*[0.1 flooring(2.5, 'tp') 1.2 0.15], 'Tag', 'volumeop1',...
                   'callback', {@pb_call, S});

%% Pump progress waitbars

% S.Q_pump1_progress = statusbar(0:3);
% set(S.Q_pump1_progress(1).ProgressBar, 'Visible', 'on');


%% Changeable rates


%% Status





end
