function [] = main_panel_pb_call(varargin)
% Function Information
% Parent - Various
% Children - iterate.m
%          - flooring.m
% Description - Changes various inputs due to pushbutton and
%               togglebutton functions; multipurpose button function
S = varargin{3};  %main figure handle
U = varargin{1};  %current uicontrol
str = char(U.String);
switch str
    case 'Find Devices'
        U.String = strjoin({char(8635),'Refresh','List'});
        U.UserData = 0;  % function that finds pumps
        U.Parent = S.fig;
        U.FontSize = 0.65;
        U.Position = S.lb_quitone.Position;
        switch U.UserData
            case 0
                S.DeviceListZero = uicontrol(S.Main,'style','text','units','normalized',...
                                        'position',[0 flooring(2.3,'b') 1 3*S.panel_struct.btn_h],...
                                        'BackgroundColor',S.Main.BackgroundColor,'ForegroundColor',S.color.drk_gry,...
                                        'FontUnits','normalized','FontWeight','bold','FontSize',0.11,...
                                        'string','No pumps were found','Tag','Device 0','Visible','On');                                     
                U.UserData = 1; %Testing purposes only
            case 1
                S.DeviceListOne = uicontrol(S.Main,'style','pushbutton','units','normalized',...
                                        'position',[S.panel_struct.coln(2) flooring(5,'b') ...
                                         S.panel_struct.coln(3)-S.panel_struct.coln(2)+...
                                         S.panel_struct.btn_w S.panel_struct.btn_h],...
                                        'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
                                        'FontUnits','normalized','FontWeight','bold','FontSize',0.4,...                   
                                        'string','Pump Number 1','Tag','Device 1','Visible','On');        
                U.UserData = 2; %Testing purposes only                
            case 2
                S.DeviceListOne = uicontrol(S.Main,'style','pushbutton','units','normalized',...
                                        'position',[S.panel_struct.coln(2) flooring(5.5,'b') ...
                                         S.panel_struct.coln(3)-S.panel_struct.coln(2)+...
                                         S.panel_struct.btn_w S.panel_struct.btn_h],...
                                        'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
                                        'FontUnits','normalized','FontWeight','bold','FontSize',0.4,...                   
                                        'string','Pump Number 1','Tag','Device 1','Visible','On');
                S.DeviceListTwo = uicontrol(S.Main,'style','pushbutton','units','normalized',...
                                        'position',[S.panel_struct.coln(2) flooring(3.5,'b') ...
                                         S.panel_struct.coln(3)-S.panel_struct.coln(2)+...
                                         S.panel_struct.btn_w S.panel_struct.btn_h],...
                                        'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
                                        'FontUnits','normalized','FontWeight','bold','FontSize',0.4,...                   
                                        'string','Pump Number 2','Tag','Device 2','Visible','On');                                    
                U.UserData = 3; %Testing purposes only
            case 3
                S.DeviceListOne = uicontrol(S.Main,'style','pushbutton','units','normalized',...
                                        'position',[S.panel_struct.coln(2) flooring(5.8,'b') ...
                                         S.panel_struct.coln(3)-S.panel_struct.coln(2)+...
                                         S.panel_struct.btn_w S.panel_struct.btn_h],...
                                        'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
                                        'FontUnits','normalized','FontWeight','bold','FontSize',0.4,...                   
                                        'string','Pump Number 1','Tag','Device 1','Visible','On');
                S.DeviceListTwo = uicontrol(S.Main,'style','pushbutton','units','normalized',...
                                        'position',[S.panel_struct.coln(2) flooring(4.2,'b') ...
                                         S.panel_struct.coln(3)-S.panel_struct.coln(2)+...
                                         S.panel_struct.btn_w S.panel_struct.btn_h],...
                                        'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
                                        'FontUnits','normalized','FontWeight','bold','FontSize',0.4,...                   
                                        'string','Pump Number 2','Tag','Device 2','Visible','On');  
                S.DeviceListTre = uicontrol(S.Main,'style','pushbutton','units','normalized',...
                                        'position',[S.panel_struct.coln(2) flooring(2.6,'b') ...
                                         S.panel_struct.coln(3)-S.panel_struct.coln(2)+...
                                         S.panel_struct.btn_w S.panel_struct.btn_h],...
                                        'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
                                        'FontUnits','normalized','FontWeight','bold','FontSize',0.4,...                   
                                        'string','Pump Number 3','Tag','Device 3','Visible','On');                                      
                U.UserData = 4; %Testing purposes only
            case 4
                S.DeviceListOne = uicontrol(S.Main,'style','pushbutton','units','normalized',...
                                        'position',[S.panel_struct.btn_w/4 flooring(5.5,'b') ...
                                         S.panel_struct.coln(3)-S.panel_struct.coln(2)+...
                                         S.panel_struct.btn_w/2 S.panel_struct.btn_h],...
                                        'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
                                        'FontUnits','normalized','FontWeight','bold','FontSize',0.4,...                   
                                        'string','Pump Number 1','Tag','Device 1','Visible','On');
                S.DeviceListTwo = uicontrol(S.Main,'style','pushbutton','units','normalized',...
                                        'position',[S.panel_struct.btn_w/4+.5 flooring(5.5,'b') ...
                                         S.panel_struct.coln(3)-S.panel_struct.coln(2)+...
                                         S.panel_struct.btn_w/2 S.panel_struct.btn_h],...
                                        'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
                                        'FontUnits','normalized','FontWeight','bold','FontSize',0.4,...                   
                                        'string','Pump Number 2','Tag','Device 2','Visible','On');  
                S.DeviceListTre = uicontrol(S.Main,'style','pushbutton','units','normalized',...
                                        'position',[S.panel_struct.btn_w/4 flooring(3.5,'b') ...
                                         S.panel_struct.coln(3)-S.panel_struct.coln(2)+...
                                         S.panel_struct.btn_w/2 S.panel_struct.btn_h],...
                                        'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
                                        'FontUnits','normalized','FontWeight','bold','FontSize',0.4,...                   
                                        'string','Pump Number 3','Tag','Device 3','Visible','On');                                      
                S.DeviceListFor = uicontrol(S.Main,'style','pushbutton','units','normalized',...
                                        'position',[S.panel_struct.btn_w/4+.5 flooring(3.5,'b') ...
                                         S.panel_struct.coln(3)-S.panel_struct.coln(2)+...
                                         S.panel_struct.btn_w/2 S.panel_struct.btn_h],...
                                        'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
                                        'FontUnits','normalized','FontWeight','bold','FontSize',0.4,...                   
                                        'string','Pump Number 4','Tag','Device 4','Visible','On');                  
                U.UserData = 5; %Testing purposes only                
            case 5
            case 6
            case 7
            case 8
            case 9
            otherwise
        end
%         if isempty(findobj('Tag','Device 0'))
%                 S.DeviceListZero = uicontrol(S.Main,'style','text','units','normalized',...
%                                         'position',[0 flooring(2.3,'b') 1 3*S.panel_struct.btn_h],...
%                                         'BackgroundColor',S.Main.BackgroundColor,'ForegroundColor',S.color.drk_gry,...
%                                         'FontUnits','normalized','FontWeight','bold','FontSize',0.11,...
%                                         'string','No pumps were found','Tag','Device 0','Visible','Off');
%         end
%         if isempty(findobj('Tag','Device 1'))        
%                 S.DeviceListOne = uicontrol(S.Main,'style','pushbutton','units','normalized',...
%                                         'position',[0 flooring(2.3,'b') 1 3*S.panel_struct.btn_h],...
%                                         'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
%                                         'FontUnits','normalized','FontWeight','bold','FontSize',0.11,...                 
%                                         'string','Pump Number 1','Tag','Device 1','Visible','Off');
%                 S.DeviceListOne.String
%         end
%         if isempty(findobj('Tag','Device 2'))                                    
%                 S.DeviceListTwo = uicontrol(S.Main,'style','pushbutton','units','normalized',...
%                                         'position',[0 flooring(2.3,'b') 1 3*S.panel_struct.btn_h],...
%                                         'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
%                                         'FontUnits','normalized','FontWeight','bold','FontSize',0.11,...                 
%                                         'string','Pump Number 2','Tag','Device 2','Visible','Off');
%         end
%         if isempty(findobj('Tag','Device 3'))                                    
%                 S.DeviceListTre = uicontrol(S.Main,'style','pushbutton','units','normalized',...
%                                         'position',[0 flooring(2.3,'b') 1 3*S.panel_struct.btn_h],...
%                                         'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
%                                         'FontUnits','normalized','FontWeight','bold','FontSize',0.11,...                 
%                                         'string','Pump Number 3','Tag','Device 3','Visible','Off');
%         end
%         if isempty(findobj('Tag','Device 4'))                                    
%                 S.DeviceListFor = uicontrol(S.Main,'style','pushbutton','units','normalized',...
%                                         'position',[0 flooring(2.3,'b') 1 3*S.panel_struct.btn_h],...
%                                         'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
%                                         'FontUnits','normalized','FontWeight','bold','FontSize',0.11,...                 
%                                         'string','Pump Number 4','Tag','Device 4','Visible','Off');
%         end
%         if isempty(findobj('Tag','Device 5'))                                    
%                 S.DeviceListFiv = uicontrol(S.Main,'style','pushbutton','units','normalized',...
%                                         'position',[0 flooring(2.3,'b') 1 3*S.panel_struct.btn_h],...
%                                         'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
%                                         'FontUnits','normalized','FontWeight','bold','FontSize',0.11,...                 
%                                         'string','Pump Number 5','Tag','Device 5','Visible','Off');
%         end
%         if isempty(findobj('Tag','Device 6'))                                    
%                 S.DeviceListSix = uicontrol(S.Main,'style','pushbutton','units','normalized',...
%                                         'position',[0 flooring(2.3,'b') 1 3*S.panel_struct.btn_h],...
%                                         'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
%                                         'FontUnits','normalized','FontWeight','bold','FontSize',0.11,...                 
%                                         'string','Pump Number 6','Tag','Device 6','Visible','Off');
%         end
%         if isempty(findobj('Tag','Device 7'))                                    
%                 S.DeviceListSvn = uicontrol(S.Main,'style','pushbutton','units','normalized',...
%                                         'position',[0 flooring(2.3,'b') 1 3*S.panel_struct.btn_h],...
%                                         'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
%                                         'FontUnits','normalized','FontWeight','bold','FontSize',0.11,...                 
%                                         'string','Pump Number 1','Tag','Device 7','Visible','Off');
%         end
%         if isempty(findobj('Tag','Device 8'))                                    
%                 S.DeviceListEit = uicontrol(S.Main,'style','pushbutton','units','normalized',...
%                                         'position',[0 flooring(2.3,'b') 1 3*S.panel_struct.btn_h],...
%                                         'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
%                                         'FontUnits','normalized','FontWeight','bold','FontSize',0.11,...                 
%                                         'string','Pump Number 2','Tag','Device 8','Visible','Off');
%         end
%         if isempty(findobj('Tag','Device 9'))                                    
%                 S.DeviceListNin = uicontrol(S.Main,'style','pushbutton','units','normalized',...
%                                         'position',[0 flooring(2.3,'b') 1 3*S.panel_struct.btn_h],...
%                                         'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
%                                         'FontUnits','normalized','FontWeight','bold','FontSize',0.11,...                 
%                                         'string','Pump Number 3','Tag','Device 9','Visible','Off');
%         end
        disp('bad job');
    case strjoin({char(8635),'Refresh','List'})
        disp('good job');
        if isempty(findobj('Tag','Device 0'))
                S.DeviceListZero = uicontrol(S.Main,'style','text','units','normalized',...
                                        'position',[0 flooring(2.3,'b') 1 3*S.panel_struct.btn_h],...
                                        'BackgroundColor',S.Main.BackgroundColor,'ForegroundColor',S.color.drk_gry,...
                                        'FontUnits','normalized','FontWeight','bold','FontSize',0.11,...
                                        'string','No pumps were found','Tag','Device 0','Visible','Off');
        end
        if isempty(findobj('Tag','Device 1'))        
                S.DeviceListOne = uicontrol(S.Main,'style','pushbutton','units','normalized',...
                                        'position',[0 flooring(2.3,'b') 1 3*S.panel_struct.btn_h],...
                                        'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
                                        'FontUnits','normalized','FontWeight','bold','FontSize',0.4,...                 
                                        'string','Pump Number 1','Tag','Device 1','Visible','Off');
        end
        if isempty(findobj('Tag','Device 2'))                                    
                S.DeviceListTwo = uicontrol(S.Main,'style','pushbutton','units','normalized',...
                                        'position',[0 flooring(2.3,'b') 1 3*S.panel_struct.btn_h],...
                                        'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
                                        'FontUnits','normalized','FontWeight','bold','FontSize',0.4,...                 
                                        'string','Pump Number 2','Tag','Device 2','Visible','Off');
        end
        if isempty(findobj('Tag','Device 3'))                                    
                S.DeviceListTre = uicontrol(S.Main,'style','pushbutton','units','normalized',...
                                        'position',[0 flooring(2.3,'b') 1 3*S.panel_struct.btn_h],...
                                        'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
                                        'FontUnits','normalized','FontWeight','bold','FontSize',0.4,...                 
                                        'string','Pump Number 3','Tag','Device 3','Visible','Off');
        end
        if isempty(findobj('Tag','Device 4'))                                    
                S.DeviceListFor = uicontrol(S.Main,'style','pushbutton','units','normalized',...
                                        'position',[0 flooring(2.3,'b') 1 3*S.panel_struct.btn_h],...
                                        'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
                                        'FontUnits','normalized','FontWeight','bold','FontSize',0.4,...                 
                                        'string','Pump Number 4','Tag','Device 4','Visible','Off');
        end
        if isempty(findobj('Tag','Device 5'))                                    
                S.DeviceListFiv = uicontrol(S.Main,'style','pushbutton','units','normalized',...
                                        'position',[0 flooring(2.3,'b') 1 3*S.panel_struct.btn_h],...
                                        'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
                                        'FontUnits','normalized','FontWeight','bold','FontSize',0.4,...                 
                                        'string','Pump Number 5','Tag','Device 5','Visible','Off');
        end
        if isempty(findobj('Tag','Device 6'))                                    
                S.DeviceListSix = uicontrol(S.Main,'style','pushbutton','units','normalized',...
                                        'position',[0 flooring(2.3,'b') 1 3*S.panel_struct.btn_h],...
                                        'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
                                        'FontUnits','normalized','FontWeight','bold','FontSize',0.4,...                 
                                        'string','Pump Number 6','Tag','Device 6','Visible','Off');
        end
        if isempty(findobj('Tag','Device 7'))                                    
                S.DeviceListSvn = uicontrol(S.Main,'style','pushbutton','units','normalized',...
                                        'position',[0 flooring(2.3,'b') 1 3*S.panel_struct.btn_h],...
                                        'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
                                        'FontUnits','normalized','FontWeight','bold','FontSize',0.4,...                 
                                        'string','Pump Number 1','Tag','Device 7','Visible','Off');
        end
        if isempty(findobj('Tag','Device 8'))                                    
                S.DeviceListEit = uicontrol(S.Main,'style','pushbutton','units','normalized',...
                                        'position',[0 flooring(2.3,'b') 1 3*S.panel_struct.btn_h],...
                                        'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
                                        'FontUnits','normalized','FontWeight','bold','FontSize',0.4,...                 
                                        'string','Pump Number 2','Tag','Device 8','Visible','Off');
        end
        if isempty(findobj('Tag','Device 9'))                                    
                S.DeviceListNin = uicontrol(S.Main,'style','pushbutton','units','normalized',...
                                        'position',[0 flooring(2.3,'b') 1 3*S.panel_struct.btn_h],...
                                        'BackgroundColor',S.color.drk_gry,'ForegroundColor',S.color.blk,...
                                        'FontUnits','normalized','FontWeight','bold','FontSize',0.4,...                 
                                        'string','Pump Number 3','Tag','Device 9','Visible','Off');
        end        
        S.DeviceListZero.Visible = 'Off';
        S.DeviceListOne.Visible = 'Off';
        S.DeviceListTwo.Visible = 'Off';
        S.DeviceListTre.Visible = 'Off';
        S.DeviceListFor.Visible = 'Off';
        S.DeviceListFiv.Visible = 'Off';
        S.DeviceListSix.Visible = 'Off';
        S.DeviceListSvn.Visible = 'Off';
        S.DeviceListEit.Visible = 'Off';    
        S.DeviceListNin.Visible = 'Off';
        switch U.UserData
            case 0
                S.DeviceListZero.Visible = 'On';                                     
                U.UserData = 1; %Testing purposes only
            case 1
                S.DeviceListOne.Position = [S.panel_struct.coln(2) flooring(5,'b') ...
                                            S.panel_struct.coln(3)-S.panel_struct.coln(2)+...
                                            S.panel_struct.btn_w S.panel_struct.btn_h];
                S.DeviceListOne.Visible = 'On';               
                U.UserData = 2; %Testing purposes only 
            case 2
                S.DeviceListOne.Position = [S.panel_struct.coln(2) flooring(5.5,'b') ...
                                            S.panel_struct.coln(3)-S.panel_struct.coln(2)+...
                                            S.panel_struct.btn_w S.panel_struct.btn_h];
                S.DeviceListOne.Visible = 'On';
                S.DeviceListTwo.Position = [S.panel_struct.coln(2) flooring(3.5,'b') ...
                                            S.panel_struct.coln(3)-S.panel_struct.coln(2)+...
                                            S.panel_struct.btn_w S.panel_struct.btn_h];
                S.DeviceListTwo.Visible = 'On';                                   
                U.UserData = 3; %Testing purposes only
            case 3
                S.DeviceListOne.Position = [S.panel_struct.coln(2) flooring(5.8,'b') ...
                                            S.panel_struct.coln(3)-S.panel_struct.coln(2)+...
                                            S.panel_struct.btn_w S.panel_struct.btn_h];
                S.DeviceListOne.Visible = 'On';
                S.DeviceListTwo.Position = [S.panel_struct.coln(2) flooring(4.2,'b') ...
                                            S.panel_struct.coln(3)-S.panel_struct.coln(2)+...
                                            S.panel_struct.btn_w S.panel_struct.btn_h];
                S.DeviceListTwo.Visible = 'On';
                S.DeviceListTre.Position = [S.panel_struct.coln(2) flooring(2.6,'b') ...
                                            S.panel_struct.coln(3)-S.panel_struct.coln(2)+...
                                            S.panel_struct.btn_w S.panel_struct.btn_h];
                S.DeviceListTre.Visible = 'On';                             
                U.UserData = 4; %Testing purposes only
            case 4
                S.DeviceListOne.Position = [S.panel_struct.btn_w/4 flooring(5.5,'b') ...
                                            S.panel_struct.coln(3)-S.panel_struct.coln(2)+...
                                            S.panel_struct.btn_w/2 S.panel_struct.btn_h];
                S.DeviceListOne.Visible = 'On';
                S.DeviceListTwo.Position = [S.panel_struct.btn_w/4+.5 flooring(5.5,'b') ...
                                            S.panel_struct.coln(3)-S.panel_struct.coln(2)+...
                                            S.panel_struct.btn_w/2 S.panel_struct.btn_h];
                S.DeviceListTwo.Visible = 'On';
                S.DeviceListTre.Position = [S.panel_struct.btn_w/4 flooring(3.5,'b') ...
                                            S.panel_struct.coln(3)-S.panel_struct.coln(2)+...
                                            S.panel_struct.btn_w/2 S.panel_struct.btn_h];
                S.DeviceListTre.Visible = 'On';
                S.DeviceListFor.Position = [S.panel_struct.btn_w/4+.5 flooring(3.5,'b') ...
                                            S.panel_struct.coln(3)-S.panel_struct.coln(2)+...
                                            S.panel_struct.btn_w/2 S.panel_struct.btn_h];
                S.DeviceListFor.Visible = 'On';               
                U.UserData = 5; %Testing purposes only 
            case 5
            case 6
            case 7
            case 8
            case 9
            otherwise
        end              
end
end
