function S = Syrris_Asia_panel_setup(varargin)
% Function Information
% Parent - PanelSet.m
% Additions - S.Asia 
%           - S.L_back          
%           - S.R_back            
%           - S.Lch
%           - S.Rch
%           - S.Llbl_fill
%           - S.Lstr_fill
%           - S.Ltopminipb_fill
%           - S.Lbotminipb_fill
%           - S.Llbl_empty
%           - S.Lstr_empty      
%           - S.Ltopminipb_empty
%           - S.Lbotminipb_empty
%           - S.Llbl_pump
%           - S.Lstr_pump     
%           - S.Ltopminipb_pump
%           - S.Lbotminipb_pump
%           - S.Lstat_bar
%           - S.Lstat_bar            
%           - S.Lstat_state
%           - S.Lstat_state
%           - S.Lstat_pump
%           - S.Lstat_pump            
%           - S.Lstat_err
%           - S.Lstat_err           
%           - S.Lstat_lop
%           - S.Lstat_lop             
%           - S.Lpb_fill
%           - S.Lpb_empty
%           - S.Lpb_pump
%           - S.Lpb_stop
%           - S.Rlbl_fill
%           - S.Rstr_fill    
%           - S.Rtopminipb_fill
%           - S.Rbotminipb_fill
%           - S.Rlbl_empty
%           - S.Rstr_empty
%           - S.Rtopminipb_empty
%           - S.Rbotminipb_empty             
%           - S.Rlbl_pump
%           - S.Rstr_pump              
%           - S.Rtopminipb_pump
%           - S.Rbotminipb_pump          
%           - S.Rstat_bar
%           - S.Rstat_bar             
%           - S.Rstat_state
%           - S.Rstat_state
%           - S.Rstat_pump
%           - S.Rstat_pump               
%           - S.Rstat_err
%           - S.Rstat_err           
%           - S.Rstat_lop;
%           - S.Rstat_lop             
%           - S.Rpb_fill
%           - S.Rpb_empty
%           - S.Rpb_pump
%           - S.Rpb_stop
% Description - Creates Syrris Asia panel and all of the
%               functions and interfaces associated with
%               this particular pump
S = varargin{1};
K = varargin{2}; %figure handle
%% Deconstruction
btn_w = S.panel_struct.btn_w;
btn_h = S.panel_struct.btn_h;
lbl_h = S.panel_struct.lbl_h;
flb_h = S.panel_struct.flb_h;
arr_w = S.panel_struct.arr_w;
panel_w = S.panel_struct.panel_w;
clr = S.panel_struct.clr;
edit_clr = S.panel_struct.edit_clr;
panpos = S.panel_struct.panpos;
coln = S.panel_struct.coln;
Max = S.panel_struct.Max;
Min = S.panel_struct.Min;
upper = S.panel_struct.upper;
red = S.color.red;
blu = S.color.blu;
grn = S.color.grn;
ppl = S.color.ppl;
org = S.color.org;
wht = S.color.wht;
blk = S.color.blk;
lit_red = S.color.lit_red;
lit_blu = S.color.lit_blu;
lit_grn = S.color.lit_grn;
lit_ppl = S.color.lit_ppl;
lit_org = S.color.lit_org;

%% Asia Panel
S.Asia = uipanel(K,'BorderType','none','BackgroundColor',clr,'Visible','off','Position',panpos,'Tag',strcat('Asia_',num2str(K.UserData)));
addpath H:\008\AsiaLabviewAPI\mfiles;
%mex -setup C;
%if not(libisloaded('AsiaPumpInterface'))
%    addpath H:\008\AsiaLabviewAPI;
    %loadlibrary('AsiaPumpInterface.dll','AsiaPumpInterface.h');    
%     loadlibrary('AsiaPumpInterface');
%end
if(~exist('pumpIndex','var')) %set defaults
    LerrorCode = 0;         RerrorCode = 0;
    LpumpState = 0;         RpumpState = 0;
    LpumpRate  = 0;         RpumpRate  = 0;
    Lpressure  = 0;         Rpressure  = 0;
    LlastOverPressure = 0;  RlastOverPressure = 0;
    Lptr_errorCode.Value = LerrorCode;                Rptr_errorCode.Value = RerrorCode;
    Lptr_pumpState.Value = LpumpState;                Rptr_pumpState.Value = RpumpState;
    Lptr_pumpRate.Value  = LpumpRate;                 Rptr_pumpRate.Value  = RpumpRate;
    Lptr_pressure.Value  = Lpressure;                 Rptr_pressure.Value  = Rpressure;
    Lptr_lastOverPressure.Value = LlastOverPressure;  Rptr_lastOverPressure.Value = RlastOverPressure;
    LpumpStateStr = 'Uninitialized';                  RpumpStateStr = 'Uninitialized';
end
%     folder = fileparts(mfilename('fullpath'));
%     javaclasspath( {folder, [folder '\JTattoo.jar']} );    
%pumpIndex = scanForAsiaPumps;
pumpIndex = 0;
%enterRemoteMode(pumpIndex);
S.pb_quitone.ForegroundColor = S.lb_quitone.ForegroundColor;
S.pb_quitone.BackgroundColor = S.lb_quitone.BackgroundColor;
S.pb_quitall.ForegroundColor = S.lb_quitone.ForegroundColor;
S.pb_quitall.BackgroundColor = S.lb_quitone.BackgroundColor;
switch pumpIndex
    case 0
        channel_control;    % Channel activation pushbuttons
        left_channel;       % Left channel control
        right_channel;      % Right channel control
    otherwise
        no_pumps_detected;  % No pumps detected        
end

    function no_pumps_detected
        S.Back  = uipanel(S.Asia,'Visible','on','position',[0 0 1 1],'BackgroundColor',edit_clr,'BorderType','none');       
        S.Title = uicontrol(S.Asia,'style','text','units','normalized',...
                 'position',[0 flooring(4.5,'b') 1 3*btn_h],'BackgroundColor',S.Back.BackgroundColor,...
                 'FontUnits','normalized','FontWeight','bold','FontSize',0.13,'string','No pumps detected');
    end
    function channel_control
        S.L_back = uipanel(S.Asia,'Visible','on','position',[0 0 panel_w 1],'BackgroundColor',clr*0.3,'BorderType','none');%'etchedout');             
        S.R_back = uipanel(S.Asia,'Visible','on','position',[1-panel_w 0 panel_w 1],'BackgroundColor',clr*0.3,'BorderType','none');%'etchedout');             
        S.Lch = uicontrol(S.Asia,'style','togglebutton','units','normalized',...
                         'position',[coln(1) flooring(8,'b') coln(2)+btn_w-coln(1) btn_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','Left Channel Activation','BackgroundColor', (clr.*0.7),'callback',{@pb_call,S});
        S.Rch = uicontrol(S.Asia,'style','togglebutton','units','normalized',...
                        'position',[coln(3) flooring(8,'b') coln(4)+btn_w-coln(3) btn_h],...
                        'FontUnits','normalized','FontWeight','bold',...                 
                        'string','Right Channel Activation','BackgroundColor', (clr.*0.7),'callback',{@pb_call,S});             
    end       
    function left_channel
        if time_call(1,'sec','exact')
            disp('pumpStatusCheck');
            LerrorCode = Lptr_errorCode.Value;
            LpumpState = Lptr_pumpState.Value;
            LpumpRate  = Lptr_pumpRate.Value;
            Lpressure  = Lptr_pressure.Value;
            LlastOverPressure = Lptr_lastOverPressure.Value;
            Lptr_errorCode = libpointer('int32Ptr',LerrorCode);
            Lptr_pumpState = libpointer('int32Ptr',LpumpState);    
            Lptr_pumpRate = libpointer('singlePtr',LpumpRate);
            Lptr_pressure = libpointer('singlePtr',Lpressure);     
            Lptr_lastOverPressure = libpointer('singlePtr',LlastOverPressure);
            calllib('H:\008\AsiaLabviewAPI\mfiles','pumpStatus',pumpIndex,0,Lptr_errorCode,...
                    Lptr_pumpState,Lptr_pumpRate,Lptr_pressure,Lptr_lastOverPressure)
            switch  Lptr_pumpState.Value
                case -1;    LpumpStateStr = 'Error';
                case 0;     LpumpStateStr = 'Uninitialized';
                case 1;     LpumpStateStr = 'Initializing';
                case 2;     LpumpStateStr = 'Idle';
                case 3;     LpumpStateStr = 'Filling';
                case 4;     LpumpStateStr = 'Idle (Full)';
                case 5;     LpumpStateStr = 'Emptying';
                case 6;     LpumpStateStr = 'Idle (Empty)';
                case 7;     LpumpStateStr = 'Pumping';
                otherwise;  LpumpStateStr = 'Error';
            end
        end

        %% Changeable Rates
        % Fill rate
        S.Llbl_fill = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(1)+arr_w flooring(7.5,'tp') btn_w-arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','Fill rate (ul/min)','BackgroundColor',lit_blu,'callback',{@pb_call,S});
        S.Lstr_fill = uicontrol(S.Asia,'style','edit','units','normalized',...
                         'position',[coln(1)+arr_w flooring(7,'fl') btn_w-arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','10','BackgroundColor',edit_clr,'callback',{@edit_call,S});
        S.Ltopminipb_fill = uicontrol(S.Asia,'style','pushbutton','units','normalized',...
                         'position',[coln(1) flooring(7.5,'tp') arr_w flb_h],'Tag','Scroll',...
                         'FontUnits','normalized','FontWeight','bold','FontName','Symbol',...                 
                         'string',char(9650),'BackgroundColor', (clr.*0.7),'callback',{@pb_call,S});
        S.Lbotminipb_fill = uicontrol(S.Asia,'style','pushbutton','units','normalized',...
                         'position',[coln(1) flooring(7,'fl') arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold','FontName','Symbol',...                 
                         'string',char(9660),'BackgroundColor', (clr.*0.7),'callback',{@pb_call,S});          
        % Empty rate
        S.Llbl_empty = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(1)+arr_w flooring(6.5,'tp') btn_w-arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','Empty rate (ul/min)','BackgroundColor',lit_ppl,...
                         'callback',{@pb_call,S});
        S.Lstr_empty = uicontrol(S.Asia,'style','edit','units','normalized',...
                         'position',[coln(1)+arr_w flooring(6,'fl') btn_w-arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','10','BackgroundColor',edit_clr,'callback',{@edit_call,S});      
        S.Ltopminipb_empty = uicontrol(S.Asia,'style','pushbutton','units','normalized',...
                         'position',[coln(1) flooring(6.5,'tp') arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold','FontName','Symbol',...                 
                         'string',char(9650),'BackgroundColor', (clr.*0.7),'callback',{@pb_call,S});
        S.Lbotminipb_empty = uicontrol(S.Asia,'style','pushbutton','units','normalized',...
                         'position',[coln(1) flooring(6,'fl') arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold','FontName','Symbol',...                 
                         'string',char(9660),'BackgroundColor', (clr.*0.7),'callback',{@pb_call,S});             
        % Pump rate (entered)
        S.Llbl_pump = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(1)+arr_w flooring(5.5,'tp') btn_w-arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','Pump rate (ul/min)','BackgroundColor',lit_grn,'callback',{@pb_call,S});
        S.Lstr_pump = uicontrol(S.Asia,'style','edit','units','normalized',...
                         'position',[coln(1)+arr_w flooring(5,'fl') btn_w-arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','10','BackgroundColor',edit_clr,'callback',{@edit_call,S});      
        S.Ltopminipb_pump = uicontrol(S.Asia,'style','pushbutton','units','normalized',...
                         'position',[coln(1) flooring(5.5,'tp') arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold','FontName','Symbol',...                 
                         'string',char(9650),'BackgroundColor', (clr.*0.7),'callback',{@pb_call,S});
        S.Lbotminipb_pump = uicontrol(S.Asia,'style','pushbutton','units','normalized',...
                         'position',[coln(1) flooring(5,'fl') arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold','FontName','Symbol',...                 
                         'string',char(9660),'BackgroundColor', (clr.*0.7),'callback',{@pb_call,S});
        %% Status
        % Pressure
        S.Lstat_bar = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(2) flooring(3.5,'l') btn_w lbl_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','Pressure (bar)','BackgroundColor',lit_org,'callback',{@pb_call,S});
        S.Lstatlbar = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(2) flooring(3,'l') btn_w lbl_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string',num2str(Lptr_pressure.Value),'BackgroundColor',edit_clr);  
        % Pump State             
        S.Lstat_state = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(1) flooring(4.5,'l') btn_w lbl_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','Pump State','BackgroundColor',lit_org,'callback',{@pb_call,S});
        S.Lstatlstate = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(1) flooring(4,'l') btn_w lbl_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string',LpumpStateStr,'BackgroundColor',edit_clr);  
        % Pump rate (observed)
        S.Lstat_pump = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(1) flooring(3.5,'l') btn_w lbl_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','Pump rate','BackgroundColor',lit_org,'callback',{@pb_call,S});
        S.Lstatlpump = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(1) flooring(3,'l') btn_w lbl_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string',num2str(Lptr_pumpRate.Value),'BackgroundColor',edit_clr);     
        % Error Code             
        S.Lstat_err = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(1) flooring(2.5,'l') btn_w lbl_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','Error Code','BackgroundColor',lit_org,'callback',{@pb_call,S});
        S.Lstatlerr = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(1) flooring(2,'l') btn_w lbl_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string',num2str(Lptr_errorCode.Value),'BackgroundColor',edit_clr);    
        % Last Over Pressure             
        S.Lstat_lop = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(2) flooring(2.5,'l') btn_w lbl_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','Last Over Pressure','BackgroundColor',lit_org,'callback',{@pb_call,S});
        S.Lstatllop = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(2) flooring(2,'l') btn_w lbl_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string',num2str(Lptr_lastOverPressure.Value),'BackgroundColor',edit_clr);                
        %% Push buttons (Fill, Empty, Pump, Stop)
        S.Lpb_fill = uicontrol(S.Asia,'style','push','units','normalized',...
                         'position',[coln(2) flooring(7,'b') btn_w btn_h],...
                         'FontUnits','normalized','FontWeight','bold','ForegroundColor',wht,...                 
                         'string','FILL','BackgroundColor',blu,'callback',{@pb_call,S});
        S.Lpb_empty = uicontrol(S.Asia,'style','push','units','normalized',...
                         'position',[coln(2) flooring(6,'b') btn_w btn_h],...
                         'FontUnits','normalized','FontWeight','bold','ForegroundColor',wht,...                 
                         'string','EMPTY','BackgroundColor',ppl,'callback',{@pb_call,S});
        S.Lpb_pump = uicontrol(S.Asia,'style','push','units','normalized',...
                         'position',[coln(2) flooring(5,'b') btn_w btn_h],...
                         'FontUnits','normalized','FontWeight','bold','ForegroundColor',wht,...               
                         'string','PUMP','BackgroundColor',grn,'callback',{@pb_call,S});
        S.Lpb_stop = uicontrol(S.Asia,'style','push','units','normalized',...
                         'position',[coln(2) flooring(4,'b') btn_w btn_h],...
                         'FontUnits','normalized','FontWeight','bold','ForegroundColor',wht,...        
                         'string','STOP','BackgroundColor',red,'callback',{@pb_call,S});         
%% Java stuff
%     Spinner_Values = Min:upper:Max;
%     jspinner = javax.swing.JSpinner(Spinner_Values);
%     jspinner.setValue(25);
%     placeJavaComponent(jspinner,S.Lstr_fill.Position,S.Asia);
%     set(jspinner,'StateChangedCallback',callbackFunc);
    end
    function right_channel
         if time_call(1,'sec','exact')
            disp('pumpStatusCheck');
            RerrorCode = Rptr_errorCode.Value;
            RpumpState = Rptr_pumpState.Value;
            RpumpRate  = Rptr_pumpRate.Value;
            Rpressure  = Rptr_pressure.Value;
            RlastOverPressure = Rptr_lastOverPressure.Value;
            Rptr_errorCode = libpointer('int32Ptr',RerrorCode);
            Rptr_pumpState = libpointer('int32Ptr',RpumpState);    
            Rptr_pumpRate = libpointer('singlePtr',RpumpRate);
            Rptr_pressure = libpointer('singlePtr',Rpressure);     
            Rptr_lastOverPressure = libpointer('singlePtr',RlastOverPressure);
            calllib('mfiles','pumpStatus',pumpIndex,0,Rptr_errorCode,...
                    Rptr_pumpState,Rptr_pumpRate,Rptr_pressure,Rptr_lastOverPressure)
            switch  Rptr_pumpState.Value
                case -1;    RpumpStateStr = 'Error';
                case 0;     RpumpStateStr = 'Uninitialized';
                case 1;     RpumpStateStr = 'Initializing';
                case 2;     RpumpStateStr = 'Idle';
                case 3;     RpumpStateStr = 'Filling';
                case 4;     RpumpStateStr = 'Idle (Full)';
                case 5;     RpumpStateStr = 'Emptying';
                case 6;     RpumpStateStr = 'Idle (Empty)';
                case 7;     RpumpStateStr = 'Pumping';
                otherwise;  RpumpStateStr = 'Error';
            end
        end
        %% Changeable Rates
        % Fill rate
        S.Rlbl_fill = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(3)+arr_w flooring(7.5,'tp') btn_w-arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','Fill rate (ul/min)','BackgroundColor',lit_blu,'callback',{@pb_call,S});
        S.Rstr_fill = uicontrol(S.Asia,'style','edit','units','normalized',...
                         'position',[coln(3)+arr_w flooring(7,'fl') btn_w-arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','10','BackgroundColor',edit_clr,'callback',{@edit_call,S});     
        S.Rtopminipb_fill = uicontrol(S.Asia,'style','pushbutton','units','normalized',...
                         'position',[coln(3) flooring(7.5,'tp') arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold','FontName','Symbol',...                 
                         'string',char(9650),'BackgroundColor', (clr.*0.7),'callback',{@pb_call,S});
        S.Rbotminipb_fill = uicontrol(S.Asia,'style','pushbutton','units','normalized',...
                         'position',[coln(3) flooring(7,'fl') arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold','FontName','Symbol',...                 
                         'string',char(9660),'BackgroundColor', (clr.*0.7),'callback',{@pb_call,S});
        % Empty rate
        S.Rlbl_empty = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(3)+arr_w flooring(6.5,'tp') btn_w-arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','Empty rate (ul/min)','BackgroundColor',lit_ppl,'callback',{@pb_call,S});
        S.Rstr_empty = uicontrol(S.Asia,'style','edit','units','normalized',...
                         'position',[coln(3)+arr_w flooring(6,'fl') btn_w-arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','10','BackgroundColor',edit_clr,'callback',{@edit_call,S});  
        S.Rtopminipb_empty = uicontrol(S.Asia,'style','pushbutton','units','normalized',...
                         'position',[coln(3) flooring(6.5,'tp') arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold','FontName','Symbol',...                 
                         'string',char(9650),'BackgroundColor', (clr.*0.7),'callback',{@pb_call,S});
        S.Rbotminipb_empty = uicontrol(S.Asia,'style','pushbutton','units','normalized',...
                         'position',[coln(3) flooring(6,'fl') arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold','FontName','Symbol',...                 
                         'string',char(9660),'BackgroundColor', (clr.*0.7),'callback',{@pb_call,S});             
        % Pump rate (entered)
        S.Rlbl_pump = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(3)+arr_w flooring(5.5,'tp') btn_w-arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','Pump rate (ul/min)','BackgroundColor',lit_grn,'callback',{@pb_call,S});
        S.Rstr_pump = uicontrol(S.Asia,'style','edit','units','normalized',...
                         'position',[coln(3)+arr_w flooring(5,'fl') btn_w-arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','10','BackgroundColor',edit_clr,'callback',{@edit_call,S});              
        S.Rtopminipb_pump = uicontrol(S.Asia,'style','pushbutton','units','normalized',...
                         'position',[coln(3) flooring(5.5,'tp') arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold','FontName','Symbol',...                 
                         'string',char(9650),'BackgroundColor', (clr.*0.7),'callback',{@pb_call,S});
        S.Rbotminipb_pump = uicontrol(S.Asia,'style','pushbutton','units','normalized',...
                         'position',[coln(3) flooring(5,'fl') arr_w flb_h],...
                         'FontUnits','normalized','FontWeight','bold','FontName','Symbol',...                 
                         'string',char(9660),'BackgroundColor', (clr.*0.7),'callback',{@pb_call,S});          
        %% Status
        % Pressure
        S.Rstat_bar = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(4) flooring(3.5,'l') btn_w lbl_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','Pressure (bar)','BackgroundColor',lit_org,'callback',{@pb_call,S});
        S.Rstatrbar = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(4) flooring(3,'l') btn_w lbl_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string',num2str(Rptr_pressure.Value),'BackgroundColor',edit_clr);  
        % Pump State
        S.Rstat_state = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(3) flooring(4.5,'l') btn_w lbl_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','Pump State','BackgroundColor',lit_org,'callback',{@pb_call,S});
        S.Rstatrstate = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(3) flooring(4,'l') btn_w lbl_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string',RpumpStateStr,'BackgroundColor',edit_clr);  
        % Pump rate (observed)
        S.Rstat_pump = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(3) flooring(3.5,'l') btn_w lbl_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','Pump rate','BackgroundColor',lit_org,'callback',{@pb_call,S});
        S.Rstatrpump = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(3) flooring(3,'l') btn_w lbl_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string',num2str(Rptr_pumpRate.Value),'BackgroundColor',edit_clr);     
        % Error Code             
        S.Rstat_err = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(3) flooring(2.5,'l') btn_w lbl_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','Error Code','BackgroundColor',lit_org,'callback',{@pb_call,S});
        S.Rstatrerr = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(3) flooring(2,'l') btn_w lbl_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string',num2str(Rptr_errorCode.Value),'BackgroundColor',edit_clr);    
        % Last Over Pressure             
        S.Rstat_lop = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(4) flooring(2.5,'l') btn_w lbl_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string','Last Over Pressure','BackgroundColor',lit_org,'callback',{@pb_call,S});
        S.Rstatrlop = uicontrol(S.Asia,'style','text','units','normalized',...
                         'position',[coln(4) flooring(2,'l') btn_w lbl_h],...
                         'FontUnits','normalized','FontWeight','bold',...                 
                         'string',num2str(Rptr_lastOverPressure.Value),'BackgroundColor',edit_clr);                       
        %% Push buttons (Fill, Empty, Pump, Stop)             
        S.Rpb_fill = uicontrol(S.Asia,'style','push','units','normalized',...
                         'position',[coln(4) flooring(7,'b') btn_w btn_h],...
                         'FontUnits','normalized','FontWeight','bold','ForegroundColor',wht,...                 
                         'string','FILL','BackgroundColor',blu,'callback',{@pb_call,S});
        S.Rpb_empty = uicontrol(S.Asia,'style','push','units','normalized',...
                         'position',[coln(4) flooring(6,'b') btn_w btn_h],...
                         'FontUnits','normalized','FontWeight','bold','ForegroundColor',wht,...                
                         'string','EMPTY','BackgroundColor',ppl,'callback',{@pb_call,S});
        S.Rpb_pump = uicontrol(S.Asia,'style','push','units','normalized',...
                         'position',[coln(4) flooring(5,'b') btn_w btn_h],...
                         'FontUnits','normalized','FontWeight','bold','ForegroundColor',wht,...            
                         'string','PUMP','BackgroundColor',grn,'callback',{@pb_call,S});
        S.Rpb_stop = uicontrol(S.Asia,'style','push','units','normalized',...
                         'position',[coln(4) flooring(4,'b') btn_w btn_h],...
                         'FontUnits','normalized','FontWeight','bold','ForegroundColor',wht,...                
                         'string','STOP','BackgroundColor',red,'callback',{@pb_call,S});
    end
end

% Place a Java component within a panel in a specified normalized position
function placeJavaComponent ( jcomponent, position, parent )
    jcomponent = javaObjectEDT( jcomponent );  % ensure component is auto-delegated to EDT
    jcomponent.setOpaque(false);  % useful to demonstrate L&F backgrounds
    [jc,hContainer] = javacomponent( jcomponent, [], parent ); %#ok<ASGLU>
    set(hContainer, 'Units','Normalized', 'Position',position);
end  % placeJavaComponent
